"""my tables

Revision ID: e34af2e6ea35
Revises: 
Create Date: 2023-10-05 23:13:48.253989

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e34af2e6ea35'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=255), nullable=False),
    sa.Column('book_publication_year', sa.Integer(), nullable=True),
    sa.Column('book_author_id', sa.Integer(), nullable=False),
    sa.Column('book_genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['book_genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
# ### end Alembic commands ###
def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('genre')
    op.drop_table('author')
    # ### end Alembic commands ###